import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#c4abff",
        "on-surface": "#e2e2e8",
        "tertiary-container": "#b71bcf",
        "secondary-fixed-dim": "#d0bcff",
        "surface-container": "#1e2024",
        "on-surface-variant": "#c4c5d9",
        "surface-container-highest": "#333539",
        "tertiary-fixed-dim": "#fbabff",
        secondary: "#d0bcff",
        "on-primary-container": "#efefff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0c0e12",
        surface: "#111317",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "surface-container-high": "#282a2e",
        "on-secondary": "#3c0091",
        "on-tertiary-fixed": "#36003e",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#23005c",
        "primary-container": "#2e5bff",
        "surface-variant": "#333539",
        "on-primary-fixed-variant": "#0035be",
        "on-background": "#e2e2e8",
        "on-primary": "#002388",
        "surface-tint": "#b8c3ff",
        "surface-dim": "#111317",
        "on-tertiary-container": "#ffebfb",
        "on-error": "#690005",
        "secondary-fixed": "#e9ddff",
        "on-tertiary-fixed-variant": "#7c008e",
        "outline-variant": "#434656",
        "inverse-surface": "#e2e2e8",
        primary: "#b8c3ff",
        "on-secondary-fixed-variant": "#5516be",
        "surface-bright": "#37393e",
        "inverse-primary": "#124af0",
        "primary-fixed-dim": "#b8c3ff",
        "on-tertiary": "#580065",
        tertiary: "#fbabff",
        "tertiary-fixed": "#ffd6fd",
        outline: "#8e90a2",
        "on-primary-fixed": "#001356",
        background: "#111317",
        "surface-container-low": "#1a1c20",
        "inverse-on-surface": "#2f3035",
        "secondary-container": "#571bc1",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config;

